### ISSUE TITLE
DNN 9.13.3 Error

### ISSUE THREAD

**Issue by rfrobenius** [ChrisHammond/dnnsimplearticle#5]
I tried installing simplearticle on a blank DNN 9.13.03 site (localhost). I've placed the module on a page and get an error message when I try to add an article (using Xcillion theme). This is when trying to display the edit control for DNN Simple Article.

Part of the stack trace is:
Error: is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Could not load file or assembly 'DotNetNuke.Web.Deprecated' or one of its dependencies. The system cannot find the file specified. ---> System.Web.HttpParseException: Could not load file or assembly 'DotNetNuke.Web.Deprecated' or one of its dependencies. The system cannot find the file specified. 

At first guess it seems that the DotNetNuke.Web.Deprecated is no longer distributed with this DNN release.

Anyways, I'm hoping to learn from the code and modify the module to host a rudimentary catalog.

**Comment by ChrisHammond** [comment]
Thanks, I'll give this a check to see if I can recreate and come up with a simple fix

**Comment by ChrisHammond** [comment]
https://github.com/ChrisHammond/dnnsimplearticle/tree/main/install

You can grab the latest install ZIP file from that folder and try it out. I'll work on getting a release out soon (possibly)

**Comment by rfrobenius** [comment]
Looks like it works now. Thanks!

**Comment by ChrisHammond** [comment]
I just spent some time removing the reference to this DLL and testing the module, looks like it wasn't actually needed. I'll do some more testing before release to make sure it still works in other scenarios, but I was able to get the module working without including the DLL going forward.

**Comment by rfrobenius** [comment]
I had a question about the module: how does one manage the categories for the articles. I looked at the vocabularies section of the site but didn't get anywhere.

Thanks-

Rex
________________________________

**Comment by ChrisHammond** [comment]
Rex, I'll have to get back to you on that. I honestly can't remember, and can't get them working myself :D
